security:
    # Définition des encodeurs de mot de passe pour les utilisateurs
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définition des fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api:
            pattern: ^/api
            access_token:
                token_handler: App\Security\AccessTokenHandler
            stateless: true

        # Route de développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    # Contrôle d'accès
    access_control:
        # Définir les règles d'accès pour les routes protégées
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }