version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/symfony/dockerfile
    volumes:
      - ./:/var/www/symfony
    networks:
      - carner.net

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./:/var/www/symfony
    ports:
      - "80:80"
    networks:
      - carner.net
    depends_on:
      - php-fpm

  database:
    image: mariadb
    networks:
      - carner.net
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=Carner
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    networks:
      - carner.net
    ports:
      - "8080:8080"

networks:
  carner.net:
    driver: bridge