version: "3"

services:

  web:
    build: docker/symfony
    restart: always
    networks:
      - carner.net
    ports:
      - "8077:80"
    volumes:
      - ./docker/symfony/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www

  database:
    image: mariadb
    networks:
      - carner.net
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=carner
    ports:
      - '3307:3306'

  adminer:
    image: adminer
    networks:
      - carner.net
    ports:
      - "8007:8080"

networks:
  carner.net:
    external: true