version: "3"

services:
  database:
    image: mariadb
    networks:
      - lifesaver.net
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
      - MYSQL_DATABASE=lifesaver
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    networks:
      - lifesaver.net
    ports:
      - "8080:8080"

networks:
  lifesaver.net:
    external: true