FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    nginx \
    libicu-dev \
    libonig-dev \
    libzip-dev \
    && docker-php-ext-install intl opcache pdo_mysql zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/symfony

COPY ./bin ./bin
COPY ./config ./config
COPY ./docker ./docker
COPY ./migrations ./migrations
COPY ./public ./public
COPY ./src ./src
COPY .env .env
COPY composer.* symfony.lock ./

RUN composer install --no-dev --optimize-autoloader

RUN chown -R www-data:www-data /var/www/symfony \
    && chmod -R 755 /var/www/symfony

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

RUN rm /etc/nginx/sites-enabled/default

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
