# Utiliser l'image PHP-FPM
FROM php:8.3-fpm

# Installer les dépendances pour Symfony
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Définir le répertoire de travail
WORKDIR /var/www/symfony

# Copier le code de l'application
COPY . .

# Installer les dépendances de Symfony
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

EXPOSE 9000