apiVersion: v1
kind: Service
metadata:
  name: symfony-service
  labels:
    app: symfony
spec:
  selector:
    app: symfony
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
